### ISSUE TITLE
Backport 21w07a ore textures

### ISSUE THREAD

**Issue by Brun333rp** [StormDragon77/FixedInconsistencies#149] opened 2021-02-19 17:41 UTC
Ore textures, except for diamonds, have been recently changed to have unique shapes. Would be cool if we could use them in 1.16.X versions, like you did with clocks and compasses.

**Comment by StormDragon77** [comment] 2021-02-20 00:52
Duplicate of #146

**Closed by StormDragon77** 2021-02-20 00:52 UTC
Labels: duplicate, idea
